name = "TwoBit"
uuid = "75842c30-9b2d-11e9-3f58-f17fe2b89951"
authors = ["Sabrina Jaye Ward <sabrinajward@protonmail.com>"]
version = "0.2.0"

[deps]
BioGenerics = "47718e42-2ac5-11e9-14af-e5595289c2ea"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"

[compat]
BioGenerics = "0.1"
BioSequences = "3"
Documenter = "0.27"
julia = "1.6"

[extras]
FormatSpecimens = "3372ea36-2a1a-11e9-3eb7-996970b6ffbd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Documenter", "Test", "FormatSpecimens"]
